version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
